server:
  port: 8083
  servlet:
    context-path: /
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect