server:
  port: 8085
  servlet:
    context-path: /
spring:
  application:
    name: logistics-service
  datasource:
    url: jdbc:mysql://localhost:3306/microservice_demo?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
dubbo:
  application:
    name: logistics-service
    id: logistics-service
  scan:
    base-packages: service.logistics
  protocol:
    name: dubbo
    port: 10085
  registry:
    address: N/A
  consumer:
    filter: consumerFilter
  provider:
    filter: providerFilter
#    address: zookeeper://127.0.0.1:2181
embedded:
  zookeeper:
    port: 2181
collector:
  host: localhost
  port: 10058