spring:
  application:
    name: backend

collector:
  host: 127.0.0.1
  port: 10058

server:
  port: 10078
embedded:
  zookeeper:
    port: 2181

dubbo:
  protocol:
    name: dubbo
    port: 10088
  application:
    name: backend
#  registry:
#    address: zookeeper://127.0.0.1:2181
#    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

debug: true